# Generated by Django 6.0.2 on 2026-02-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campus_area', models.CharField(choices=[('main', 'Main Campus'), ('engineering', 'Engineering Block'), ('north', 'North Block'), ('sports', 'Sports Complex'), ('other', 'Other')], default='main', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canteens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('dietary', 'Dietary'), ('cuisine', 'Cuisine'), ('interest', 'Interest'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('distance', models.IntegerField(help_text='Distance in minutes walk')),
                ('dietary', models.CharField(choices=[('veg', 'Vegetarian'), ('vegan', 'Vegan'), ('non-veg', 'Non-Veg'), ('all', 'All')], default='all', max_length=10)),
                ('image', models.CharField(default='🍽️', help_text='Emoji icon', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='recommendations.canteen')),
                ('tags', models.ManyToManyField(blank=True, related_name='food_items', to='recommendations.tag')),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['-rating', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('distance', models.IntegerField(help_text='Distance in minutes walk')),
                ('image', models.CharField(default='📅', help_text='Emoji icon', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=100)),
                ('registered_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recommendations.canteen')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='recommendations.tag')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-rating', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=250)),
                ('dietary', models.CharField(default='all', max_length=10)),
                ('location', models.CharField(default='any', max_length=50)),
                ('available_time', models.IntegerField(default=30)),
                ('interests', models.JSONField(default=list)),
                ('weight_price', models.IntegerField(default=50)),
                ('weight_rating', models.IntegerField(default=70)),
                ('weight_distance', models.IntegerField(default=40)),
                ('preferred_categories', models.JSONField(default=list, help_text='List of preferred category tags')),
                ('budget_level', models.CharField(choices=[('low', 'Low (≤ ₹100)'), ('medium', 'Medium (₹101 - ₹300)'), ('high', 'High (> ₹300)')], default='medium', max_length=10)),
                ('preferred_distance', models.IntegerField(default=15, help_text='Preferred max walking distance in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('event', 'Event')], max_length=10)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('action', models.CharField(choices=[('shown', 'Shown'), ('clicked', 'Clicked'), ('ordered', 'Ordered'), ('dismissed', 'Dismissed')], default='shown', max_length=10)),
                ('is_explore', models.BooleanField(default=False, help_text='Was this an anti-filter-bubble suggestion')),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'item_type', 'action'], name='recommendat_user_id_298860_idx'), models.Index(fields=['user', 'created_at'], name='recommendat_user_id_38c571_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('event', 'Event')], max_length=10)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_places',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
