# Generated by Django 6.0.2 on 2026-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationlog',
            name='item_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='savedplace',
            name='item_id',
            field=models.BigIntegerField(),
        ),
    ]
